### ISSUE TITLE
Add text to front page

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mm#1]
https://idbs-engineering.com/ is also built with Minimal Mistakes template. It has following text at the front page: 

> IDBS provides Enterprise SaaS scientific informatics software platform powering R&D organizations, scientists and teams, in biologics development, drug discovery and development - idbs.com
> But you're not here for that, are you? You are here because you'd like to find out more about the engineering culture and team behind our products 

How can I add similar text above _Recent posts_ in https://epogrebnyak.github.io/mm/

**Comment by necelentano** [comment]
Added mock text to _layout/home.html file.

**Comment by epogrebnyak** [comment]
@necelentano  - а `{{ content }}` никак нельзя задействовать в home.html чтобы текст брать откуда-то из отдельного файла?

**Comment by epogrebnyak** [comment]
Примерно как тут говорят: https://github.com/mmistakes/minimal-mistakes/issues/1426#issuecomment-354303200

**Comment by necelentano** [comment]
{{ content }} берется из файла index.html в корне сайта. Можно прямо там (в index.html) писать (но по умолчанию там почему то написано, что не желательно его редактировать). Если редактировать index.html (index.md) то _layout/home.html можно вообще удалить. Layout Splash используется для построения кастомных страниц вроде [Главной страницы](https://mmistakes.github.io/minimal-mistakes/). Есть Hero Image на всю ширину, с заголовком, описанием, кнопкой, а под ним еще три блока в feature_row (тоже со своими картинками, заголовком, описанием и ссылками на разделы).

**Comment by necelentano** [comment]
Попробовал создать файл _pages/index.md (front matter указал layout: home и permalink: /). То есть можно добавлять нужное содержание в _pages/index.md (либо назвать main.md, но не home.md – последний вариант названия почему то не работает, может конфликт в теме, не знаю) и не трогать index.html в корне сайта.

**Comment by epogrebnyak** [comment]
По-моему то что нужно. Не думали, `author_profile: true` может нам false
здесь нужен?

ср, 26 авг. 2020 г., 16:48 Андрей | Andrey <notifications@github.com>:

**Comment by necelentano** [comment]
Да, работает) Хотя, вроде бы пробовал и не работало. Нужно хорошенько почитать доку. Сейчас исправлю, как нужно.

**Comment by epogrebnyak** [comment]
В этих генераторах сайтов по-моему только если сам писал этот генератор можено с уверенностью говорить, что понимаешь как работает )

Спасибо за помощь!
